apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: s3.i.as216455.net
  namespace: traefik
spec:
  entryPoints:
    - internal
    - internalsecure
  routes:
    - kind: Rule
      match: Host(`s3.i.as216455.net`)
      services:
        - kind: Service
          name: ceph-rgw
          namespace: traefik
          port: 7480
    - kind: Rule
      match: HostRegexp(`^.+\.s3\.i\.as216455\.net$`)
      services:
        - kind: Service
          name: ceph-rgw
          namespace: traefik
          port: 7480

  tls:
    secretName: s3.i.as216455.net-prod-tls
