apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: loki-k8s
  namespace: monitoring
spec:
  store: k8s-objectstore-ssd
  displayName: loki-k8s
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-k8s
  namespace: monitoring
spec:
  generateBucketName: loki-k8s
  storageClassName: ceph-objectstore-ssd-pve
  additionalConfig:
    bucketOwner: "loki-k8s"
