apiVersion: v1
kind: Service
metadata:
  name: mqtt2prometheus
  namespace: monitoring
  labels:
    app: mqtt2prometheus
spec:
  selector:
    app: mqtt2prometheus
  type: ClusterIP
  ports:
    - name: metrics
      protocol: TCP
      port: 9641
      targetPort: metrics
